name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        type: [Release, Debug]
        platform:
          - name: Emscripten
            target: hello-gl
            configure: -DEMSCRIPTEN=ON
            env: 
              CXX: em++
              CC: emcc
          - name: Desktop
            target: test
            dependencies: libgl-dev libvulkan-dev libssl-dev libwayland-dev libxkbcommon-dev xorg-dev
            configure: -DGLFW_BUILD_WAYLAND=ON -DGLFW_BUILD_X11=ON

    runs-on: ${{matrix.os}}

    container:
      image: emscripten/emsdk

    env:
      CXX: ${{matrix.platform.env.CXX}}
      CC: ${{matrix.platform.env.CC}}

    steps:
    - name: Install Dependencies
      run: sudo apt-get update && apt-get install -y ${{matrix.platform.dependencies}}

    - name: Install shaderc
      run: wget -r -nd https://storage.googleapis.com/shaderc/badges/build_link_linux_clang_release.html && sudo tar -xzv -f install.tgz --strip-components=2 -C /usr/bin install/bin

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        lfs: true
        clean: false
  
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{matrix.type}} ${{matrix.platform.configure}}

    - name: Build
      run: cmake --build build --config ${{matrix.type}} --target ${{matrix.platform.target}}

    - uses: actions/upload-artifact@v4
      if: ${{ !env.ACT }}
      id: upload-build
      with:
        name: build-${{matrix.type}}-${{matrix.platform.name}}
        path: build/bin
        if-no-files-found: error
        compression-level: 9
    
