# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CXX: em++ 
  CC: emcc

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    container:
     image: emscripten/emsdk
     
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    steps:
    - name: Install Dependencies
      run: | 
        wget -c https://storage.googleapis.com/shaderc/artifacts/prod/graphics_shader_compiler/shaderc/linux/continuous_clang_release/386/20220812-081917/install.tgz -O - | sudo tar -xzv --strip-components=2 -C /usr/bin install/bin
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
      
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DEMSCRIPTEN=ON

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Make temporary directory
      run: mkdir -p ${{runner.temp}}

    - name: Setup Pages
      uses: actions/configure-pages@v1
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: build/source
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@main
